import React, { Fragment } from "react";
import { pack, hierarchy } from "d3-hierarchy";


const NodeInformation = defaultProps => {
    const [data, setData] = React.useState([]);
    const [size, setSize] = React.useState({ width: 200, height: 200 });

    React.useEffect(() => {
        if (defaultProps.size) setSize(defaultProps.size);

        if (defaultProps.data !== data) {
            setData(defaultProps.data);
        }
        setData(defaultProps.data);

    }, [defaultProps]);

    const sampleData = {
        "children":
            [
                { name: "Master", pop: 13, color: '#88DD00' },
                { name: "Node", pop: 5, color: '#6A6A6A' },
                { name: "Node", pop: 5, color: '#6A6A6A' },
            ]
    };

    const nodes = hierarchy(sampleData)
        .sum(function (d) { return d.pop; });

    const packLayout = pack(sampleData)
        .size([size.width, size.height])
        .padding(10)

    const root = packLayout(nodes)

    const Bubbles = ({ nodes }) => {
        return nodes.map((node, i) => (
            <Fragment key={i}>
                <Bubble key={node.name} leaf={node} />
                {node.children && <Bubbles nodes={node.children} />}
            </Fragment>
        ))
    }

    const Bubble = ({ leaf }) => {
        // Use x and y coordinates generated by D3 pack layout to position
        // an SVG group.
        const emojiSize = Math.max(14, leaf.r / 4)
        return <g transform={`translate(${leaf.x},${leaf.y})`}>
            <circle
                r={leaf.r}
                fill={leaf.data.color}
            >
                <title>
                    {leaf.data.name} - {leaf.data.pop || leaf.value}M
                </title>
            </circle>
            <text
                y={emojiSize / 2.3}
                style={{ fontSize: `${emojiSize}px`, textAnchor: 'middle' }}
                fill="#fff"
            >
                {leaf.data.name}
            </text>
        </g>
    }

    return (
        <div style={{ width: "100%", height: "100%", }}>
            <svg width={size.width} height={size.height}>
                <Bubbles nodes={root.children} />
            </svg>
        </div>
    );
};

export default NodeInformation;
