ARG CONSOLE_IMAGE
FROM $CONSOLE_IMAGE AS builder

WORKDIR /edge-cloud-ui

ARG REACT_APP_CAPTCHA_V2_KEY
ARG REACT_APP_GA_MEASUREMENT_ID
ENV REACT_APP_CAPTCHA_V2_KEY=$REACT_APP_CAPTCHA_V2_KEY
ENV REACT_APP_GA_MEASUREMENT_ID=$REACT_APP_GA_MEASUREMENT_ID

RUN npm run build

FROM nginx:stable

COPY docker-nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /edge-cloud-ui/build /usr/share/nginx/html
