let data = [
    [
        "2020-05-16T13:13:39.532652117Z",
        0,
        0,
        0,
        0,
        2,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        "mexplat-stage-hamburg-cloudlet",
        "TDG",
        null,
        0,
        "FindCloudlet",
        null,
        2,
        "2.0"
    ],
    [
        "2020-05-16T13:13:38.530093302Z",
        1,
        0,
        0,
        0,
        5,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        1,
        "RegisterClient",
        null,
        6,
        "2.0"
    ],
    [
        "2020-05-16T13:13:35.529605136Z",
        1,
        0,
        0,
        0,
        4,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        1,
        "RegisterClient",
        null,
        5,
        "2.0"
    ],
    [
        "2020-05-16T13:11:08.049814247Z",
        1,
        0,
        0,
        0,
        3,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        1,
        "RegisterClient",
        null,
        4,
        "2.0"
    ],
    [
        "2020-05-16T13:11:06.04944347Z",
        1,
        0,
        0,
        0,
        2,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        1,
        "RegisterClient",
        null,
        3,
        "2.0"
    ],
    [
        "2020-05-16T13:10:56.029599188Z",
        0,
        0,
        0,
        0,
        1,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        "mexplat-stage-hamburg-cloudlet",
        "TDG",
        null,
        0,
        "FindCloudlet",
        null,
        1,
        "2.0"
    ],
    [
        "2020-05-16T13:10:55.029407299Z",
        1,
        0,
        0,
        0,
        1,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        1,
        "RegisterClient",
        null,
        2,
        "2.0"
    ],
    [
        "2020-05-16T13:10:52.959834468Z",
        0,
        0,
        0,
        0,
        1,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        0,
        "RegisterClient",
        null,
        1,
        "2.0"
    ],
    [
        "2020-05-16T01:35:45.536192064Z",
        0,
        0,
        0,
        0,
        1,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        "mexplat-stage-hamburg-cloudlet",
        "TDG",
        null,
        0,
        "FindCloudlet",
        null,
        1,
        "2.0"
    ],
    [
        "2020-05-16T01:35:44.536000652Z",
        0,
        0,
        0,
        0,
        3,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        0,
        "RegisterClient",
        null,
        3,
        "2.0"
    ],
    [
        "2020-05-16T01:35:42.535649129Z",
        0,
        0,
        0,
        0,
        1,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        0,
        "GetAppInstList",
        null,
        1,
        "2.0"
    ],
    [
        "2020-05-16T01:35:42.535649129Z",
        0,
        0,
        0,
        0,
        2,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        0,
        "RegisterClient",
        null,
        2,
        "2.0"
    ],
    [
        "2020-05-16T01:35:41.535497617Z",
        0,
        0,
        0,
        0,
        1,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        0,
        "RegisterClient",
        null,
        1,
        "2.0"
    ],
    [
        "2020-05-13T15:43:39.563164716Z",
        0,
        0,
        0,
        0,
        1,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        0,
        "GetAppInstList",
        null,
        1,
        "2.0"
    ],
    [
        "2020-05-13T15:43:38.56297287Z",
        0,
        0,
        0,
        0,
        5,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        0,
        "RegisterClient",
        null,
        5,
        "2.0"
    ],
    [
        "2020-05-13T07:56:31.226071808Z",
        0,
        0,
        0,
        0,
        2,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        "mexplat-stage-hamburg-cloudlet",
        "TDG",
        null,
        0,
        "FindCloudlet",
        null,
        2,
        "2.0"
    ],
    [
        "2020-05-13T07:56:30.225889916Z",
        0,
        0,
        0,
        0,
        4,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        0,
        "RegisterClient",
        null,
        4,
        "2.0"
    ],
    [
        "2020-05-13T07:56:28.225347929Z",
        0,
        0,
        0,
        0,
        3,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        null,
        null,
        null,
        0,
        "RegisterClient",
        null,
        3,
        "2.0"
    ],
    [
        "2020-05-13T05:27:35.529882324Z",
        0,
        0,
        0,
        0,
        1,
        "MobiledgeX SDK Demo",
        "MobiledgeX",
        "0",
        "mexplat-stage-cloudlet",
        "TDG",
        null,
        0,
        "mexplat-stage-hamburg-cloudlet",
        "TDG",
        null,
        0,
        "FindCloudlet",
        null,
        1,
        "2.0"
    ],
    [
        "2020-05-13T05:27:33.529641601Z",///time
        0,
        0,
        0,
        0,
        2,
        "MobiledgeX SDK Demo",//app
        "MobiledgeX",//orgainzation
        "0",// cellid
        "mexplat-stage-cloudlet", //cloudlet
        "TDG", //cloudlet 주인
        null,//dev
        0,// erro
        null,// foundCloudlet
        null, // foundOpertator
        null, //iid
        0,//inf
        "RegisterClient", //method
        null,//oper
        2,// reqs
        "2.0" // version
    ]
]
//    ["time", "100ms", "10ms", "25ms", "50ms", "5ms", "app", "apporg", "cellID", "cloudlet", "cloudletorg", "dev", "errs", "foundCloudlet", "foundOperator", "id", "inf", "method", "oper", "reqs", "ver",]
// ["RegisterClient", "VerifyLocation", "FindCloudlet", "GetLocation", "AppInstList", "FqdnList", "DynamicLocGroup", "QosPosition"]


let RegisterClientCount = 0;
let FindCloudletCount = 0;
let VerifyLocationCount = 0
let app = '';
let apporg = '';
let cellID = '';
let cloudlet = '';
let cloudletorg = '';
let ver = ''

data.map(item => {
    console.log(`sdlkflskdfkl====>`, item);
    let methodType = item[17];
    if (methodType === "RegisterClient") {
        RegisterClientCount++;
    }
    if (methodType === "FindCloudlet") {
        FindCloudletCount++;
    }
    if (methodType === "VerifyLocation") {
        FindCloudletCount++;
    }

    app = item[6]//app
    apporg = item[7]//.apporg
    cellID = item[8]//.cellID
    cloudlet = item[9]//.cloudlet
    cloudletorg = item[10]//.cloudletorg
    ver = item[20]//.ver
})

let metricSumDataOne = {
    RegisterClientCount,
    FindCloudletCount,
    VerifyLocationCount,
    app,
    apporg,
    cellID,
    cloudlet,
    cloudletorg,
    ver,
}

console.log(`sdlkflskdfkl====>`, metricSumDataOne);
