export const ACTION_LABEL = 'ActionLabel'
export const ACTION_WARNING = 'ActionWarning'
export const ACTION_DISABLE = 'ActionDisable'
export const ACTION_VISIBLE = 'ActionVisible'

export const ACTION_POOL_ACCESS_DEVELOPER = 'PoolAccess'
export const ACTION_POOL_ACCESS_DEVELOPER_REJECT = 'Reject'
export const ACTION_POOL_ACCESS_ADMIN_CONFIRM = 'AdminConfirm'
export const ACTION_POOL_ACCESS_ADMIN_REMOVE = 'AdminRemove'

export const ACTION_AUDIT = 'ACTION_AUDIT'
export const ACTION_ADD_USER = 'ACTION_ADD_USER'
export const ACTION_EDGE_BOX_ENABLE = 'ACTION_EDGE_BOX_ENABLE'
export const ACTION_UPDATE = 'Update'
export const ACTION_DELETE = 'Delete'
export const ACTION_TERMINAL = 'Terminal'
export const ACTION_POWER_ON = 'Power On'
export const ACTION_POWER_OFF = 'Power Off'
export const ACTION_REBOOT = 'Reboot'
export const ACTION_REFRESH = 'Refresh'
export const ACTION_UPGRADE = 'Upgrade'
export const ACTION_BILLING_ADD_CHILD = 'AddChild'
export const ACTION_BILLING_REMOVE_CHILD = 'RemovedChild'
export const ACTION_MANIFEST = 'Show Manifest'