
let usageList = [
    [
        {
            "instance": {
                "uuid": "48a8382d-cfaf-4590-bb55-9105d12f0238",
                "Region": "EU",
                "OrganizationName": "WonhoOrg1",
                "AppName": "BICAPP",
                "Version": "1.0",
                "Operator": "TDG",
                "Cloudlet": "frankfurt-eu",
                "ClusterInst": "autoclusterbicapp",
                "CloudletLocation": {
                    "latitude": 50.110924,
                    "longitude": 8.682127
                },
                "URI": "autoclusterbicapp.frankfurt-eu.tdg.mobiledgex.net",
                "Liveness": 1,
                "Mapped_port": [
                    {
                        "proto": 1,
                        "internal_port": 1112,
                        "public_port": 1112
                    }
                ],
                "Flavor": "m4.medium",
                "State": 5,
                "Error": "-",
                "Runtime": {
                    "container_ids": [
                        "BICAPP"
                    ]
                },
                "Created": "seconds : 1579251799",
                "Progress": "",
                "Edit": [
                    "Region",
                    "DeveloperName",
                    "AppName",
                    "Version",
                    "Operator",
                    "Cloudlet",
                    "ClusterInst",
                    "CloudletLocation",
                    "State",
                    "Editable"
                ],
                "Status": {},
                "Revision": 2
            },
            "columns": [
                "time",
                "app",
                "cluster",
                "dev",
                "cloudlet",
                "operator",
                "cpu",
                "mem",
                "disk",
                "sendBytes",
                "recvBytes",
                "port",
                "active",
                "handled",
                "accepts",
                "bytesSent",
                "bytesRecvd",
                "P0",
                "P25",
                "P50",
                "P75",
                "P90",
                "P95",
                "P99",
                "P99.5",
                "P99.9",
                "P100"
            ],
            "sumCpuUsage": 0.024,
            "values": [
                [
                    "2020-01-30T04:34:35.996120034Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:27.900251316Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:19.813318299Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:11.742856123Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    0.03,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:03.700378602Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    0.05,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:55.653955164Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    0.04,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:47.608032565Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    0.03,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:39.561559103Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    0.03,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:31.5172817Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    0.03,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:15.429063425Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    0.03,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ]
            ],
            "appName": "BICAPP"
        }
    ],
    [
        {
            "instance": {
                "uuid": "48a8382d-cfaf-4590-bb55-9105d12f0238",
                "Region": "EU",
                "OrganizationName": "WonhoOrg1",
                "AppName": "BICAPP",
                "Version": "1.0",
                "Operator": "TDG",
                "Cloudlet": "frankfurt-eu",
                "ClusterInst": "autoclusterbicapp",
                "CloudletLocation": {
                    "latitude": 50.110924,
                    "longitude": 8.682127
                },
                "URI": "autoclusterbicapp.frankfurt-eu.tdg.mobiledgex.net",
                "Liveness": 1,
                "Mapped_port": [
                    {
                        "proto": 1,
                        "internal_port": 1112,
                        "public_port": 1112
                    }
                ],
                "Flavor": "m4.medium",
                "State": 5,
                "Error": "-",
                "Runtime": {
                    "container_ids": [
                        "BICAPP"
                    ]
                },
                "Created": "seconds : 1579251799",
                "Progress": "",
                "Edit": [
                    "Region",
                    "DeveloperName",
                    "AppName",
                    "Version",
                    "Operator",
                    "Cloudlet",
                    "ClusterInst",
                    "CloudletLocation",
                    "State",
                    "Editable"
                ],
                "Status": {},
                "Revision": 2
            },
            "columns": [
                "time",
                "app",
                "cluster",
                "dev",
                "cloudlet",
                "operator",
                "cpu",
                "mem",
                "disk",
                "sendBytes",
                "recvBytes",
                "port",
                "active",
                "handled",
                "accepts",
                "bytesSent",
                "bytesRecvd",
                "P0",
                "P25",
                "P50",
                "P75",
                "P90",
                "P95",
                "P99",
                "P99.5",
                "P99.9",
                "P100"
            ],
            "sumMemUsage": 226586788,
            "values": [
                [
                    "2020-01-30T04:34:35.996120034Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:27.900251316Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:19.813318299Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:11.742856123Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    323695411,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:03.700378602Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    323695411,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:55.653955164Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    323695411,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:47.608032565Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    323695411,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:39.561559103Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    323695411,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:31.5172817Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    323695411,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:15.429063425Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    323695411,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ]
            ],
            "appName": "BICAPP"
        }
    ],
    [
        {
            "instance": {
                "uuid": "48a8382d-cfaf-4590-bb55-9105d12f0238",
                "Region": "EU",
                "OrganizationName": "WonhoOrg1",
                "AppName": "BICAPP",
                "Version": "1.0",
                "Operator": "TDG",
                "Cloudlet": "frankfurt-eu",
                "ClusterInst": "autoclusterbicapp",
                "CloudletLocation": {
                    "latitude": 50.110924,
                    "longitude": 8.682127
                },
                "URI": "autoclusterbicapp.frankfurt-eu.tdg.mobiledgex.net",
                "Liveness": 1,
                "Mapped_port": [
                    {
                        "proto": 1,
                        "internal_port": 1112,
                        "public_port": 1112
                    }
                ],
                "Flavor": "m4.medium",
                "State": 5,
                "Error": "-",
                "Runtime": {
                    "container_ids": [
                        "BICAPP"
                    ]
                },
                "Created": "seconds : 1579251799",
                "Progress": "",
                "Edit": [
                    "Region",
                    "DeveloperName",
                    "AppName",
                    "Version",
                    "Operator",
                    "Cloudlet",
                    "ClusterInst",
                    "CloudletLocation",
                    "State",
                    "Editable"
                ],
                "Status": {},
                "Revision": 2
            },
            "columns": [
                "time",
                "app",
                "cluster",
                "dev",
                "cloudlet",
                "operator",
                "cpu",
                "mem",
                "disk",
                "sendBytes",
                "recvBytes",
                "port",
                "active",
                "handled",
                "accepts",
                "bytesSent",
                "bytesRecvd",
                "P0",
                "P25",
                "P50",
                "P75",
                "P90",
                "P95",
                "P99",
                "P99.5",
                "P99.9",
                "P100"
            ],
            "sumRecvBytes": 0,
            "sumSendBytes": 0,
            "values": [
                [
                    "2020-01-30T04:34:35.996120034Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    null,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:27.900251316Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    null,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:19.813318299Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    null,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:11.742856123Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    null,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:03.700378602Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    null,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:55.653955164Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    null,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:47.608032565Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    null,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:39.561559103Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    null,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:31.5172817Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    null,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:15.429063425Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    null,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ]
            ],
            "appName": "BICAPP"
        }
    ],
    [
        {
            "instance": {
                "uuid": "48a8382d-cfaf-4590-bb55-9105d12f0238",
                "Region": "EU",
                "OrganizationName": "WonhoOrg1",
                "AppName": "BICAPP",
                "Version": "1.0",
                "Operator": "TDG",
                "Cloudlet": "frankfurt-eu",
                "ClusterInst": "autoclusterbicapp",
                "CloudletLocation": {
                    "latitude": 50.110924,
                    "longitude": 8.682127
                },
                "URI": "autoclusterbicapp.frankfurt-eu.tdg.mobiledgex.net",
                "Liveness": 1,
                "Mapped_port": [
                    {
                        "proto": 1,
                        "internal_port": 1112,
                        "public_port": 1112
                    }
                ],
                "Flavor": "m4.medium",
                "State": 5,
                "Error": "-",
                "Runtime": {
                    "container_ids": [
                        "BICAPP"
                    ]
                },
                "Created": "seconds : 1579251799",
                "Progress": "",
                "Edit": [
                    "Region",
                    "DeveloperName",
                    "AppName",
                    "Version",
                    "Operator",
                    "Cloudlet",
                    "ClusterInst",
                    "CloudletLocation",
                    "State",
                    "Editable"
                ],
                "Status": {},
                "Revision": 2
            },
            "columns": [
                "time",
                "app",
                "cluster",
                "dev",
                "cloudlet",
                "operator",
                "cpu",
                "mem",
                "disk",
                "sendBytes",
                "recvBytes",
                "port",
                "active",
                "handled",
                "accepts",
                "bytesSent",
                "bytesRecvd",
                "P0",
                "P25",
                "P50",
                "P75",
                "P90",
                "P95",
                "P99",
                "P99.5",
                "P99.9",
                "P100"
            ],
            "sumDiskUsage": 0,
            "values": [
                [
                    "2020-01-30T04:34:35.996120034Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:27.900251316Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:19.813318299Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:11.742856123Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:34:03.700378602Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:55.653955164Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:47.608032565Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:39.561559103Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:31.5172817Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ],
                [
                    "2020-01-30T04:33:15.429063425Z",
                    "bicapp",
                    "autoclusterbicapp",
                    "WonhoOrg1",
                    "frankfurt-eu",
                    "TDG",
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                ]
            ],
            "appName": "BICAPP"
        }
    ],
    [
        {
            "instance": {
                "uuid": "48a8382d-cfaf-4590-bb55-9105d12f0238",
                "Region": "EU",
                "OrganizationName": "WonhoOrg1",
                "AppName": "BICAPP",
                "Version": "1.0",
                "Operator": "TDG",
                "Cloudlet": "frankfurt-eu",
                "ClusterInst": "autoclusterbicapp",
                "CloudletLocation": {
                    "latitude": 50.110924,
                    "longitude": 8.682127
                },
                "URI": "autoclusterbicapp.frankfurt-eu.tdg.mobiledgex.net",
                "Liveness": 1,
                "Mapped_port": [
                    {
                        "proto": 1,
                        "internal_port": 1112,
                        "public_port": 1112
                    }
                ],
                "Flavor": "m4.medium",
                "State": 5,
                "Error": "-",
                "Runtime": {
                    "container_ids": [
                        "BICAPP"
                    ]
                },
                "Created": "seconds : 1579251799",
                "Progress": "",
                "Edit": [
                    "Region",
                    "DeveloperName",
                    "AppName",
                    "Version",
                    "Operator",
                    "Cloudlet",
                    "ClusterInst",
                    "CloudletLocation",
                    "State",
                    "Editable"
                ],
                "Status": {},
                "Revision": 2
            },
            "columns": "",
            "sumActiveConnection": 0,
            "sumHandledConnection": 0,
            "sumAcceptsConnection": 0,
            "values": [],
            "appName": "BICAPP"
        }
    ]
]

console.log('sdlkfsldkflksdflksdlfk===>', usageList[0]);

cpuUsageList = usageList[0];

let chartDataList = [];
for (let index = 0; index < cpuUsageList.length; index++) {
    if (index < 5) {
        let temp = cpuUsageList[index].instance.AppName.toString().substring(0, 10)

        console.log('sdlkfsldkflksdflksdlfk===>', temp);
    }
}


