version: '3'
services:
  db:
    build:
      context: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  mc:
    image: "registry.mobiledgex.net:5000/mobiledgex/edge-cloud:${TAG:-latest}"
    restart: always
    depends_on:
      - db
    environment:
      db_name: "${POSTGRES_DB}"
      db_username: "${POSTGRES_USER}"
      db_password: "${POSTGRES_PASSWORD}"
      superuser: "${MC_SUPERUSER}"
      superpass: "${MC_SUPERUSER_PASSWORD}"
      VAULT_ROLE_ID: "${VAULT_ROLE_ID:?VAULT_ROLE_ID not set}"
      VAULT_SECRET_ID: "${VAULT_SECRET_ID:?VAULT_SECRET_ID not set}"
    ports:
      - "9900:9900"
      - "9389:9389"
    command:
      - mc
      - "-addr"
      - "0.0.0.0:9900"
      - "-sqlAddr"
      - "db:5432"
      - "-vaultAddr"
      - "${VAULT_ADDR}"
      - "-ldapAddr"
      - "0.0.0.0:9389"
      - "-tls"
      - "/root/tls/mex-server.crt"
      - "-tlskey"
      - "/root/tls/mex-server.key"
      - "-clientCert"
      - "/root/tls/mex-server.crt"
      - "-d"
      - "api"
volumes:
  db-data:
