# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzY3OTA4MTgsImlhdCI6MTU3NjcwNDQxOCwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.4a2fmGx-NWBDmyJuRN6Rasbay0An5rZflMmuTuVnlIvNn285cGOtJ4KNaLPx5YyxymV1IgOVDujjOJFwA0okfA
http --auth-type=jwt --auth=$SUPERPASS POST https://mc.mobiledgex.net:9900/api/v1/auth/ctrl/ShowAppInst region=EU

curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:3000/data
POST http://localhost:3000/data
Content-Type: application/json

{"key1":"value1", "key2":"value2"}

### https://mc.mobiledgex.net:9900

# curl -H "Authorization: Bearer <ACCESS_TOKEN>" http://www.example.com
POST https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowAppInst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Nzk2Njc1NzksImlhdCI6MTU3OTU4MTE3OSwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.RaO3cZNCVsENI30mhQbFaPXTCC5XQv-CUNjfZuaSUodjrp_BYTU2jVyY5klV7A6cIUN0DG8huB_wo5K6T5Dt9w

{
  "region": "EU",
  "appinst": {
    "key": {
      "app_key": {
        "developer_key": {
          "name": "kyungjoon_dev"
        }
      }
    }
  }
}

###

POST https://127.0.0.1:9900/api/v1/auth/ctrl/ShowAppInst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgwMTE4NDIsImlhdCI6MTU3NzkyNTQ0MiwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.EobJeBG1UpoXj7CQ71yjXZnuee7RTGqINB4FCYUMuGhvhltqqwyP3eHJ7kEMZpPTltvVoaSnYssi-lOo6n6zGQ

{
  "region": "US"
}


###selector( cpu, mem, disk, network )사용량 요청....matrix...

POST https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Nzk4Mzk0OTUsImlhdCI6MTU3OTc1MzA5NSwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.NhEILsD7dy1wmJ4Pm-nrYDJAI_KeY-gxkxz63L7kqjcg77c4Calxpkswd_GGnefDNoKEX_8OIK1vXykaTScOPg

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "developer_key": {
        "name": "MobiledgeX"
      }
    }
  },
  "selector": "*",
  "last": 1
}

### http --verify=false --auth-type=jwt --auth=$SUPERPASS POST https://127.0.0.1:9900/api/v1/auth/metrics/cloudlet <<< '{"region":"local","cloudlet":{"operator_key":{"name":"mexdev"},"name":"localtest"},"selector":"utilization","last":1}'

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/cloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgxMjY4NTEsImlhdCI6MTU3ODA0MDQ1MSwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.xzNfGtWMnhj2Uzeau6id4TLAyOALvqV1Lm74mM8hMRIhw7ae0RHUpronqVGAlYxNVJSOSZsykeY-jCKWmWBCUw

{
  "region": "EU",
  "cloudlet": {
    "operator_key": {
      "name": "mexadmin"
    },
    "name": "frankfurt-eu"
  },
  "selector": "utilization",
  "last": 100
}

### metrics/app_level
### Region: "EU"
### OrganizationName: "MobiledgeX" //developer_key
### AppName: "bicTestApp1112-01"
### Version: "1.0"
### Operator: "TDG"
### Cloudlet: "frankfurt-eu"
### ClusterInst: "qqqaaa"

POST https://mc-stage.mobiledgex.net:443/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODU1OTg5MDQsImlhdCI6MTU4NTUxMjUwNCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.dI9Ht3XK4GJbK429w3afFv1ELLvD1nx6lOOLJt-wi1PsMKlsehbBAlaricEVHfmtB-oEhBLEprTJfdp1xT2ekg

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "developer_key": {
        "name": "MobiledgeX"
      },
      "name": "bicTestApp1112-01",
      "version": "1.0"
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": "qqqaaa"
      },
      "cloudlet_key": {
        "operator_key": {
          "name": ""
        }
      }
    }
  },
  "starttime": "*",
  "endtime": "*",
  "last": 10,
  "selector": "cpu"
}



### http --verify=false --auth-type=jwt --auth=$SUPERPASS POST https://127.0.0.1:9900/api/v1/auth/metrics/cloudlet <<< '{"region":"local","cloudlet":{"operator_key":{"name":"mexdev"},"name":"localtest"},"selector":"utilization","last":1}'

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/cloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgxMjY4NTEsImlhdCI6MTU3ODA0MDQ1MSwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.xzNfGtWMnhj2Uzeau6id4TLAyOALvqV1Lm74mM8hMRIhw7ae0RHUpronqVGAlYxNVJSOSZsykeY-jCKWmWBCUw

{
  "region": "EU",
  "cloudlet": {
    "operator_key": {
      "name": "mexadmin"
    },
    "name": "frankfurt-eu"
  },
  "selector": "utilization",
  "last": 1
}


###

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/cloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgwMTE4NDIsImlhdCI6MTU3NzkyNTQ0MiwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.EobJeBG1UpoXj7CQ71yjXZnuee7RTGqINB4FCYUMuGhvhltqqwyP3eHJ7kEMZpPTltvVoaSnYssi-lOo6n6zGQ

{
  "region": "EU",
  "cloudlet": {
    "operator_key": {
      "name": "TDG"
    },
    "name": "frankfurt-eu"
  },
  "selector": "utilization",
  "last": 1
}

###

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Nzg3OTI3MTcsImlhdCI6MTU3ODcwNjMxNywidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.zCXUcs98hEKMtT6bga4grEFf9i2BrGmb2G5tjEaqqnAkniujN1CDtoB4NwNceQUkofeIciMyboNrkxFVluaA7w

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "developer_key": {
        "name": "MobiledgeX"
      },
      "name": "bicTestApp1112-01",
      "version": "1.0"
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": "qqqaaa"
      },
      "cloudlet_key": {
        "operator_key": {
          "name": "frankfurt-eu"
        }
      }
    }
  },
  "starttime": "2019-06-11T21:26:04Z",
  "endtime": "2019-12-31T21:26:10Z",
  "last": 6,
  "selector": "*"
}


###

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Nzg3MDU5MTcsImlhdCI6MTU3ODYxOTUxNywidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.tzWT3VrZe6Ql_AuKiw93pg618kho7m-x8dyk0Bk7m75-4wD54Vl1BVOykFQ-MsvSSPBLNzEoF7q-66m4Wfn0KA

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "developer_key": {
        "name": "WonhoOrg1"
      },
      "name": "BICAPP",
      "version": "1.0"
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": "autoclusterbicapp"
      },
      "cloudlet_key": {
        "operator_key": {
          "name": "frankfurt-eu"
        }
      }
    }
  },
  "last": 6,
  "selector": "*"
}







### Metric Lookup for All Instances

POST https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODAxNTg0OTAsImlhdCI6MTU4MDA3MjA5MCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.FZiHTIKPeX5M3smmiHnk73kgwU2o8GO-QQAE7L-rh_OZL0dsWiUYTSkWwYeltr1iGFTPAqAP9ROFYkAnjg8Xog

{
  "region": "US",
  "appinst": {
    "app_key": {
      "developer_key": {
        "name": "MobiledgeX"
      }
    }
  },
  "selector": "*",
  "last": 100,
  "starttime": "2019-06-11T21:26:00Z",
  "endtime": "2019-12-31T21:26:00Z"
}

### 오퍼레이터일때 클라우드렛 레벨의 메트릭 호출..
### 오퍼레이터일때 클라우드렛 레벨의 메트릭 호출..
### 오퍼레이터일때 클라우드렛 레벨의 메트릭 호출..

POST https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/cloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODAxNTkzOTksImlhdCI6MTU4MDA3Mjk5OSwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.ZbdOT1TWFAz9wTpiAxvMGPaO6L6pM9dEOU7tAktGccIO-F6P9vtYAqLTFDkt8OCKtb4srysQ2WLTj6UX7fr8hw

{
  "region": "EU",
  "cloudlet": {
    "operator_key": {
      "name": "TDG"
    },
    "name": "berlin-staging"
  },
  "last": 2,
  "selector": "*"
}

###


POST https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/cloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODExMjMxNzAsImlhdCI6MTU4MTAzNjc3MCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.PlCaUm_y93cCQeeK4e8-6rwP4eXOzvomWBTtT2KWKyH4So1R5R99sO6NZ0obcc_HwkHDe3nGbHcsYnNAGDo5QA

{
  "region": "EU",
  "cloudlet": {
    "operator_key": {
      "name": "TDG"
    },
    "name": "hamburg-stage"
  },
  "last": 100,
  "selector": "*"
}

### 전체 클라우드렛에 대한 상태를 콜하는 Api
### 전체 클라우드렛에 대한 상태를 콜하는 Api
### 전체 클라우드렛에 대한 상태를 콜하는 Api
### 전체 클라우드렛에 대한 상태를 콜하는 Api

POST https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowCloudletInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODA2OTYyNzYsImlhdCI6MTU4MDYwOTg3NiwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.UP63BOJHKrZmVcLRkXglc0L2LxCC7C5wkM74k3-7hUzSFfX-rQySuJgLcNtuTmkJxFnVH0gqHKkoRuZDB7BYDA

{
  "region": "EU",
  "cloudlet": {
    "key": {
      "name": "*",
      "operator_key": {
        "name": "TDG"
      }
    }
  }
}

### 앱 instance 하나에 대해서 사용량을 호출한다#######
### 앱 instance 하나에 대해서 사용량을 호출한다#######
### 앱 instance 하나에 대해서 사용량을 호출한다#######
### 앱 instance 하나에 대해서 사용량을 호출한다#######

POST https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODA2OTYyNzYsImlhdCI6MTU4MDYwOTg3NiwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.UP63BOJHKrZmVcLRkXglc0L2LxCC7C5wkM74k3-7hUzSFfX-rQySuJgLcNtuTmkJxFnVH0gqHKkoRuZDB7BYDA

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "developer_key": {
        "name": "WonhoOrg1"
      },
      "name": "BICAPP",
      "version": "1.0"
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": "autoclusterbicapp"
      },
      "cloudlet_key": {
        "operator_key": {
          "name": ""
        }
      }
    }
  },
  "starttime": "2019-06-11T21:26:04Z",
  "endtime": "2019-12-11T21:26:10Z",
  "last": 6,
  "selector": "*"
}

###/api/v1/auth/ctrl/ShowCloudlet


POST https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowCloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODA5NDM5NDQsImlhdCI6MTU4MDg1NzU0NCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.VhuKLhZ7_u9b3UfvNdI8wP51lQrGFMc5LRfWKPcnXJujRFyQqInqzbGb10FmhC0srQrAtKEEgwbGMeyqlo_DmA

{
  "region": "EU",
  "cloudlet": {
    "key": {
      "operator_key": {
        "name": "TDG"
      }
    },
    "name": "*"
  }
}

###  /api/v1/auth/orgcloudlet/show
POST https://console-stage.mobiledgex.net:443/api/v1/auth/orgcloudlet/show
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODE0MjQ3NzUsImlhdCI6MTU4MTMzODM3NSwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.RC-xurMVdK36UJaEbuE189YoBIfuBn6wov1oXXHyjbj4yxhBrK-7APvyY6WgmlFrnr9j7ABbAmJ8k61iUf8peA

{
  "region": "EU"
}

###cloudletcloudletcloudletcloudletcloudletcloudletcloudletcloudletcloudlet

POST https://console-stage.mobiledgex.net:443/api/v1/auth/events/cloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODMyMTg0MDgsImlhdCI6MTU4MzEzMjAwOCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.hC0N6SqS2r_EwB3n-x9ZDHPpz5AOvPvv0YaERDCxqIGXgcQ_BHrjVsVj8S0oQlScwu4saU-rFZOfFMiCv_s08g

{
  "region": "EU",
  "cloudlet": {
    "operator_key": {
      "name": "TDG"
    },
    "name": "hamburg-stage"
  },
  "last": 50
}


### FindCloudlet /FindCloudlet/FindCloudletFindCloudlet/FindCloudlet/FindCloudletFindCloudlet/FindCloudlet

POST https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/client
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODYzMzY5MTUsImlhdCI6MTU4NjI1MDUxNSwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.XuVuzLwSO0MmfaddvjmTtkgncSesBoh9a_-1uDAxchFL3wQORVeS-AcdX4oXDiKjP8Ur9sxEDHYvLsGK-FpccQ

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "developer_key": {
        "name": "WonhoOrg1"
      },
      "name": "autoclusterbicapp",
      "version": "1.0"
    }
  },
  "method": "FindCloudlet",
  "selector": "api",
  "last": 100
}

###
POST https://console-stage.mobiledgex.net:443//api/v1/auth/ctrl/ShowAppInst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODM0NjMyNDAsImlhdCI6MTU4MzM3Njg0MCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.Ni4Xg32qVRj6hiAzwwJ4nopBLFUWFk59K21FVZkQjDxSYy9EKwGj8pazLH-MEN4cz96nIsQuzFjhQ1e35YXw4w

{
  "region": "EU"
}


###
POST https://console-stage.mobiledgex.net:443//api/v1/auth/ctrl/ShowAppInst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODM5ODcxNjgsImlhdCI6MTU4MzkwMDc2OCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.sv519Ngf7DfTa-8po2n1JaLZw3_JV305APdgcyLFa4p4VddKUAeDhkbyZF6RJ1oPqG8vXjalIa_1Rj6LykfPjQ

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "developer_key": {
        "name": "MobiledgeX"
      }
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": "venky-test"
      },
      "cloudlet_key": {
        "operator_key": {
          "name": "TDG"
        },
        "name": "hamburg-stage"
      }
    }
  }
}

###

### @todo :https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowAppInstClient
### @todo :https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowAppInstClient
### @todo :https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowAppInstClient

POST https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowAppInstClient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODM5ODcxNjgsImlhdCI6MTU4MzkwMDc2OCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.sv519Ngf7DfTa-8po2n1JaLZw3_JV305APdgcyLFa4p4VddKUAeDhkbyZF6RJ1oPqG8vXjalIa_1Rj6LykfPjQ

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "developer_key": {
        "name": "MobiledgeX"
      }
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": "venky-test"
      },
      "cloudlet_key": {
        "operator_key": {
          "name": ""
        },
        "name": ""
      }
    }
  }
}

### ShowAppInstClient EXAMPLE
POST https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowAppInstClient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODM5ODcxNjgsImlhdCI6MTU4MzkwMDc2OCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.sv519Ngf7DfTa-8po2n1JaLZw3_JV305APdgcyLFa4p4VddKUAeDhkbyZF6RJ1oPqG8vXjalIa_1Rj6LykfPjQ

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "developer_key": {
        "name": "MobiledgeX"
      },
      "name": "MobiledgeX SDK Demo",
      "version": "2.0"
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": "autoclustermobiledgexsdkdemo"
      },
      "cloudlet_key": {
        "operator_key": {
          "name": "TDG"
        },
        "name": "hamburg-stage",
        "clusterdeveloper": "MobiledgeX"
      }
    }
  }
}


### ShowAppInstClient EXAMPLE
POST https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowAppInstClient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODM5OTU5NjUsImlhdCI6MTU4MzkwOTU2NSwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.5787Dk07m-G2N9kuB_y0f1Saps5mQv_D8Cj1VD-gslM8OtlfPvmdmZcn9jHbh5FQ6XQMfBdXGGz1WuTilYJyhA

{
  "appinstclientkey": {
    "key": {
      "app_key": {
        "developer_key": {
          "name": "MobiledgeX"
        },
        "name": "MobiledgeX SDK Demo",
        "version": "2.0"
      },
      "cluster_inst_key": {
        "cloudlet_key": {
          "name": "hamburg-stage",
          "operator_key": {
            "name": "TDG"
          }
        },
        "cluster_key": {
          "name": "autoclustermobiledgexsdkdemo"
        },
        "developer": "MobiledgeX"
      }
    }
  },
  "region": "EU"
}



###//console-stage.mobiledgex.net:443 region ShowAppInstClient  region=EU developer=MobiledgeX appname="MobiledgeX SDK Demo" appvers=2.0 operator=TDG cloudlet=hamburg-stage cluster=autoclustermobiledgexsdkdemo



###

POST https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/cluster
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODQ0Mzc5NzUsImlhdCI6MTU4NDM1MTU3NSwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.oxvDOS1v22DNbnkSrXtCdQOtSDmlXV8mc2Y33-33dVVmZXakfWKwxBTPJNXMRtp18OUd9_Yrusb-bYo-lzKqqQ
`


{
  "region": "EU",
  "clusterinst": {
    "cluster_key": {
      "name": "venky-test"
    },
    "cloudlet_key": {
      "organization": "TDG",
      "name": "hamburg-stage"
    },
    "organization": "MobiledgeX"
  },
  "last": 100,
  "selector": "*"
}

###
POST https://console-qa.mobiledgex.net:443/api/v1/auth/ctrl/ShowAppInst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODQ0Nzc5MDEsImlhdCI6MTU4NDM5MTUwMSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoiYXNodXRvc2guYmhhdHQrdGVzdHVzZXJAbW9iaWxlZGdleC5jb20iLCJraWQiOjJ9.p80xGBDbHdayXbANTvwLqhbF0O4EzAwuAd7cBe-DSEsqpDd7pGVLFQrhRtYimOeHRSzoPrqRf_4FuTV_4lByzw

{
  "region": "EU",
  "appinst": {
    "key": {
      "app_key": {
        "organization": "testmonitor"
      }
    }
  }
}

###

POST https://console-qa.mobiledgex.net:443/api/v1/auth/metrics/cloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODQ0Nzc5MDEsImlhdCI6MTU4NDM5MTUwMSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoiYXNodXRvc2guYmhhdHQrdGVzdHVzZXJAbW9iaWxlZGdleC5jb20iLCJraWQiOjJ9.p80xGBDbHdayXbANTvwLqhbF0O4EzAwuAd7cBe-DSEsqpDd7pGVLFQrhRtYimOeHRSzoPrqRf_4FuTV_4lByzw

{
  "region": "EU",
  "cloudlet": {
    "organization": "TDG",
    "name": "automationBonnCloudlet"
  },
  "last": 10,
  "selector": "*"
}






###



### ShowAppInstClient as stream

POST https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowAppInstClient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODQ1ODM3ODIsImlhdCI6MTU4NDQ5NzM4MiwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.QAtg0gPXGooXEPrZRvYaa04UmELps18HDLMGgZC7sVu8ZWPyYLQBnOmENmCxVuyg2pDmRmmQut4-hefKIQ42AQ



{
  "Region": "EU",
  "AppInstClientKey": {
    "key": {
      "app_key": {
        "name": "MobiledgeX SDK Demo",
        "organization": "MobiledgeX",
        "version": "2.0"
      },
      "cluster_inst_key": {
        "cluster_key": {
          "name": "autoclustermobiledgexsdkdemo"
        },
        "organization": "MobiledgeX",
        "cloudlet_key": {
          "name": "hamburg-stage",
          "organization": "TDG"
        }
      }
    }
  }
}


###todo:ShowCloudletShowCloudletShowCloudletShowCloudlet

POST https://console-stage.mobiledgex.net:443/api/v1/auth/ctrl/ShowCloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODk1MDg5NTMsImlhdCI6MTU4OTQyMjU1MywidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.depWPNorUTOjocEgVpQdbVRdV2OWB01gyCmRphLt1_Go6pXF15rpg0SL3HciSebIUvCPPJCmu0boC-tRSW_aYg

{
  "region": "EU",
  "cloudlet": {
    "key": {
      "operator_key": {
        "name": "TDG"
      }
    },
    "name": "*"
  }
}


###findcloudlet

POST https://console-stage.mobiledgex.net:443/api/v1/findcloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODQ2NzAzNjEsImlhdCI6MTU4NDU4Mzk2MSwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.qMa9KfVlI_F2D7P2PJHry2CJMZwugDZvkRM0Gdg-fngwfGw7pE5Juow7piy8UqRQzO5mtFpp5O7W-XXf60Dztg

{
  "carrier_name": "TDG",
  "ver": 1
}

###

POST https://console-stage.mobiledgex.net:443/api/v1/auth/events/cluster
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODQ2NzAzNjEsImlhdCI6MTU4NDU4Mzk2MSwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.qMa9KfVlI_F2D7P2PJHry2CJMZwugDZvkRM0Gdg-fngwfGw7pE5Juow7piy8UqRQzO5mtFpp5O7W-XXf60Dztg

{
  "region": "EU",
  "clusterinst": {
    "cluster_key": {
      "name": "venky-test"
    },
    "cloudlet_key": {
      "name": "berlin-staging",
      "organization": "TDG"
    },
    "organization": "MobiledgeX"
  }
}


###
POST https://console-stage.mobiledgex.net:443/api/v1/auth/events/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODQ2NzAzNjEsImlhdCI6MTU4NDU4Mzk2MSwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.qMa9KfVlI_F2D7P2PJHry2CJMZwugDZvkRM0Gdg-fngwfGw7pE5Juow7piy8UqRQzO5mtFpp5O7W-XXf60Dztg

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "organization": "MobiledgeX"
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": ""
      },
      "cloudlet_key": {
        "name": "",
        "organization": ""
      }
    }
  }
}

###
POST https://console-stage.mobiledgex.net:443/api/v1/auth/events/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODUzNjQxODQsImlhdCI6MTU4NTI3Nzc4NCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.4xc6mIR-8RQyUkTd-kCx8rTBUo8rsnpmIamMyGytvXBDEoZMCKAcIMNxN-lz5SlRmUWeXBgg8lkVvBXH5h522w

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "organization": "MobiledgeX",
      "name": "MobiledgeX SDK Demo",
      "version": "docker"
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": "venky-test"
      },
      "cloudlet_key": {
        "name": "hamburg-stage",
        "organization": "TDG"
      }
    }
  },
  "selector": "*",
  "last": 20
}

### https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/app
### https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/app
### https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/app

POST https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODU1OTkyMTgsImlhdCI6MTU4NTUxMjgxOCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.9t7_aLUb1P0LqKu9zJ809GuIjl5S7Lg1AiMEIAPGCCWWL63DCyy8VHx6SOYSQSnxq5TGuro5oI86Fdfa3hl07w

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "organization": "MobiledgeX",
      "name": "MobiledgeX SDK Demo",
      "version": "k8s"
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": "mexdemo-stage"
      },
      "cloudlet_key": {
        "name": "mexplat-stage-berlin-cloudlet",
        "organization": "TDG"
      }
    }
  },
  "selector": "*",
  "last": 20
}




### https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/app
### https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/app

POST https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/cluster
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODU2MjA4NTcsImlhdCI6MTU4NTUzNDQ1NywidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.osWgOjxCpj3_nYi4gS-qVKJQs8iwnJERJUJ8c_v90Uz-A6vGTeWVOQy0uUj3Ai9OK7YZD1dQXpVOYByU2GdBSQ

{
  "region": "EU",
  "clusterinst": {
    "cluster_key": {
      "name": "mexdemo-stage"
    },
    "cloudlet_key": {
      "organization": "TDG",
      "name": "mexplat-stage-berlin-cloudlet"
    },
    "organization": "MobiledgeX"
  },
  "last": 20,
  "selector": "*"
}

###

POST https://console-stage.mobiledgex.net:443/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODU3MTYyNTYsImlhdCI6MTU4NTYyOTg1NiwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.rO4xtriISqU4y4FaJBUtuoPrKFsODYlaHREmVCWm4236HKvxZdv271o-X7xwwX-s_pH0FSC3F6uYrPplwlfzfQ

{
  "region": "EU",
  "appinst": {
    "app_key": {
      "organization": "MobiledgeX",
      "name": "MEXPrometheusAppName",
      "version": "1.0"
    },
    "cluster_inst_key": {
      "cluster_key": {
        "name": "mexdemo-stage"
      },
      "cloudlet_key": {
        "name": "mexplat-stage-frankfurt-cloudlet",
        "organization": "TDG"
      }
    }
  },
  "selector": "*",
  "last": 10,
  "starttime": "2019-04-02T13:44:00Z",
  "endtime": "2020-03-31T13:44:00Z"
}

### registerclient
### registerclient
### registerclient
### registerclient

POST  https://eu-stage.dme.mobiledgex.net:38001/v1/registerclient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODYzMDIyNTAsImlhdCI6MTU4NjIxNTg1MCwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.wKf3ITettBkrhNhmRxneauZKT_qhJBFLrHo6JVA74rFtkZqmjH6P4IxT2PVJ63VZE5HjLWTiCQEw2Mk9UMG4kQ

{
  "app_name": "MobiledgeX SDK Demo",
  "app_vers": "k8s",
  "carrier_name": "TDG",
  "org_name": "MobiledgeX",
  "dev_name": "MobiledgeX",
  "ver": 1
}

###

POST  https://console-stage.mobiledgex.net:443/api/v1/auth/events/cluster
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODYzMzY5MTUsImlhdCI6MTU4NjI1MDUxNSwidXNlcm5hbWUiOiJreXVuZ2pvb25nbzMiLCJlbWFpbCI6ImlhbWplc3NpY2E3Nzc3N0BnbWFpbC5jb20iLCJraWQiOjJ9.XuVuzLwSO0MmfaddvjmTtkgncSesBoh9a_-1uDAxchFL3wQORVeS-AcdX4oXDiKjP8Ur9sxEDHYvLsGK-FpccQ

{
  "region": "EU",
  "clusterinst": {
    "cluster_key": {
      "name": "autoclustermobiledgexsdkdemo"
    },
    "cloudlet_key": {
      "name": "RahDemo",
      "organization": "TDG"
    },
    "organization": "MobiledgeX"
  }
}


###
