# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzY3OTA4MTgsImlhdCI6MTU3NjcwNDQxOCwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.4a2fmGx-NWBDmyJuRN6Rasbay0An5rZflMmuTuVnlIvNn285cGOtJ4KNaLPx5YyxymV1IgOVDujjOJFwA0okfA
http --auth-type=jwt --auth=$SUPERPASS POST https://mc.mobiledgex.net:9900/api/v1/auth/ctrl/ShowAppInst region=EU

curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:3000/data
POST http://localhost:3000/data
Content-Type: application/json

{"key1":"value1", "key2":"value2"}

### https://mc.mobiledgex.net:9900

# curl -H "Authorization: Bearer <ACCESS_TOKEN>" http://www.example.com
POST https://mc.mobiledgex.net:9900/api/v1/auth/ctrl/ShowAppInst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzY3OTA4MTgsImlhdCI6MTU3NjcwNDQxOCwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.4a2fmGx-NWBDmyJuRN6Rasbay0An5rZflMmuTuVnlIvNn285cGOtJ4KNaLPx5YyxymV1IgOVDujjOJFwA0okfA

{
    "region": "EU"
}

###

POST https://127.0.0.1:9900/api/v1/auth/ctrl/ShowAppInst
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgwMTE4NDIsImlhdCI6MTU3NzkyNTQ0MiwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.EobJeBG1UpoXj7CQ71yjXZnuee7RTGqINB4FCYUMuGhvhltqqwyP3eHJ7kEMZpPTltvVoaSnYssi-lOo6n6zGQ

{
    "region": "US"
}


###selector( cpu, mem, disk, network )사용량 요청....matrix...

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Nzc0OTg2NTQsImlhdCI6MTU3NzQxMjI1NCwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.MoaOnk3I0LOfUtCZybOMsYa2xJh4gI5xHT7vSakcRSCkvpQwMkP0xbLc3w2iMsrYiOI-Zm-8h3E5e7IJHiKLDw

{
    "region": "EU",
    "appinst": {
        "app_key": {
            "developer_key": {
                "name": "testaaa"
            },
            "name": "jjjkkk",
            "version": "1.0"
        },
        "cluster_inst_key": {
            "cluster_key": {
                "name": "kkkkkkk"
            },
            "cloudlet_key": {
                "name": "frankfurt-eu",
                "operator_key": {
                    "name": "TDG"
                }
            }
        }
    },
    "selector": "network",
    "last": 3
}

### http --verify=false --auth-type=jwt --auth=$SUPERPASS POST https://127.0.0.1:9900/api/v1/auth/metrics/cloudlet <<< '{"region":"local","cloudlet":{"operator_key":{"name":"mexdev"},"name":"localtest"},"selector":"utilization","last":1}'

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/cloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgxMjY4NTEsImlhdCI6MTU3ODA0MDQ1MSwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.xzNfGtWMnhj2Uzeau6id4TLAyOALvqV1Lm74mM8hMRIhw7ae0RHUpronqVGAlYxNVJSOSZsykeY-jCKWmWBCUw

{
    "region": "EU",
    "cloudlet": {
        "operator_key": {
            "name": "mexadmin"
        },
        "name": "frankfurt-eu"
    },
    "selector": "utilization",
    "last": 100
}

### metrics/app_level
### Region: "EU"
### OrganizationName: "MobiledgeX" //developer_key
### AppName: "bicTestApp1112-01"
### Version: "1.0"
### Operator: "TDG"
### Cloudlet: "frankfurt-eu"
### ClusterInst: "qqqaaa"

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgxMjY4NTEsImlhdCI6MTU3ODA0MDQ1MSwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.xzNfGtWMnhj2Uzeau6id4TLAyOALvqV1Lm74mM8hMRIhw7ae0RHUpronqVGAlYxNVJSOSZsykeY-jCKWmWBCUw

{
    "region": "EU",
    "appinst": {
        "app_key": {
            "developer_key": {
                "name": "MobiledgeX"
            },
            "name": "bicTestApp1112-01",
            "version": "1.0"
        },
        "cluster_inst_key": {
            "cluster_key": {
                "name": "qqqaaa"
            },
            "cloudlet_key": {
                "operator_key": {
                    "name": ""
                }
            }
        }
    },
    "starttime": "2019-09-11T21:26:04Z",
    "endtime": "2020-01-02T21:26:10Z",
    "last": 10,
    "selector": "cpu"
}



### http --verify=false --auth-type=jwt --auth=$SUPERPASS POST https://127.0.0.1:9900/api/v1/auth/metrics/cloudlet <<< '{"region":"local","cloudlet":{"operator_key":{"name":"mexdev"},"name":"localtest"},"selector":"utilization","last":1}'

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/cloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgxMjY4NTEsImlhdCI6MTU3ODA0MDQ1MSwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.xzNfGtWMnhj2Uzeau6id4TLAyOALvqV1Lm74mM8hMRIhw7ae0RHUpronqVGAlYxNVJSOSZsykeY-jCKWmWBCUw

{
    "region": "EU",
    "cloudlet": {
        "operator_key": {
            "name": "mexadmin"
        },
        "name": "frankfurt-eu"
    },
    "selector": "utilization",
    "last": 1
}


###

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/cloudlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgwMTE4NDIsImlhdCI6MTU3NzkyNTQ0MiwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.EobJeBG1UpoXj7CQ71yjXZnuee7RTGqINB4FCYUMuGhvhltqqwyP3eHJ7kEMZpPTltvVoaSnYssi-lOo6n6zGQ

{
    "region": "EU",
    "cloudlet": {
        "operator_key": {
            "name": "TDG"
        },
        "name": "frankfurt-eu"
    },
    "selector": "utilization",
    "last": 1
}

###

POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgwMTE4NDIsImlhdCI6MTU3NzkyNTQ0MiwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.EobJeBG1UpoXj7CQ71yjXZnuee7RTGqINB4FCYUMuGhvhltqqwyP3eHJ7kEMZpPTltvVoaSnYssi-lOo6n6zGQ

{
    "region": "EU",
    "appinst": {
        "app_key": {
            "developer_key": {
                "name": "MobiledgeX"
            },
            "name": "bicTestApp1112-01",
            "version": "1.0"
        },
        "cluster_inst_key": {
            "cluster_key": {
                "name": "qqqaaa"
            },
            "cloudlet_key": {
                "operator_key": {
                    "name": "frankfurt-eu"
                }
            }
        }
    },
    "starttime": "2019-06-11T21:26:04Z",
    "endtime": "2019-12-31T21:26:10Z",
    "last": 6,
    "selector": "cpu"
}

### https://127.0.0.1:9900/api/v1/login username=mexadmin password=mexadmin123


POST https://mc-stage.mobiledgex.net:9900/api/v1/auth/metrics/app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzgwMTE4NDIsImlhdCI6MTU3NzkyNTQ0MiwidXNlcm5hbWUiOiJtZXhhZG1pbiIsImVtYWlsIjoibWV4YWRtaW5AbW9iaWxlZGdleC5uZXQiLCJraWQiOjJ9.EobJeBG1UpoXj7CQ71yjXZnuee7RTGqINB4FCYUMuGhvhltqqwyP3eHJ7kEMZpPTltvVoaSnYssi-lOo6n6zGQ

{
    "region": "EU",
    "appinst": {
        "app_key": {
            "developer_key": {
                "name": "MobiledgeX"
            },
            "name": "bicTestApp1112-01",
            "version": "1.0"
        },
        "cluster_inst_key": {
            "cluster_key": {
                "name": "qqqaaa"
            },
            "cloudlet_key": {
                "operator_key": {
                    "name": "frankfurt-eu"
                }
            }
        }
    },
    "starttime": "2019-06-11T21:26:04Z",
    "endtime": "2019-12-31T21:26:10Z",
    "last": 6,
    "selector": "cpu"
}

###
