let clusterList = [
    {
        "uuid": "55084103-9b6e-4b66-91c4-5bab0d766af6",
        "Region": "EU",
        "ClusterName": "cluster158871680299202dockerdedicated",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "verificationCloudlet",
        "Flavor": "flavor158871680299202small",
        "IpAccess": 1,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "docker",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "729cdb8e-93a4-4337-90ad-b741648377ae",
        "Region": "EU",
        "ClusterName": "multiple",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationMunichCloudlet",
        "Flavor": "automation_api_flavor",
        "IpAccess": 3,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "kubernetes",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "32632e57-9fea-40b8-b8d0-90f914740c9c",
        "Region": "EU",
        "ClusterName": "andytls",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationDusseldorfCloudlet",
        "Flavor": "automation_api_flavor",
        "IpAccess": 3,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "kubernetes",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "e43b5866-a6a6-478f-97d9-19e14c106bef",
        "Region": "EU",
        "ClusterName": "autoclustermobiledgexsdkdemo",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationMunichCloudlet",
        "Flavor": "x1.medium",
        "IpAccess": 1,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "docker",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "7b6fe548-6159-4709-8aaa-457eb20fca17",
        "Region": "EU",
        "ClusterName": "autoclustermobiledgexsdkdemo",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationDusseldorfCloudlet",
        "Flavor": "x1.medium",
        "IpAccess": 3,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "docker",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "d3f66b22-dedf-4e57-8830-26ed36cae749",
        "Region": "EU",
        "ClusterName": "andydocker",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationDusseldorfCloudlet",
        "Flavor": "automation_api_flavor",
        "IpAccess": 1,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "docker",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "0e3076a0-5e40-4ece-95bc-c730131cf1ef",
        "Region": "EU",
        "ClusterName": "cluster158871680299202dockershared",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "verificationCloudlet",
        "Flavor": "flavor158871680299202medium",
        "IpAccess": 3,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "docker",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "04c73b89-93ce-40be-b7a7-6f49dd9b9429",
        "Region": "EU",
        "ClusterName": "multiple",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationFrankfurtCloudlet",
        "Flavor": "automation_api_flavor",
        "IpAccess": 3,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "kubernetes",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "6d897564-88fc-434a-b96f-6cda92fc1382",
        "Region": "EU",
        "ClusterName": "autoclustermobiledgexsdkdemo",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationFrankfurtCloudlet",
        "Flavor": "x1.medium",
        "IpAccess": 1,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "docker",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "9c97f1d1-3078-4f54-82ac-0e1aec5da668",
        "Region": "EU",
        "ClusterName": "mutiple",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationBerlinCloudlet",
        "Flavor": "automation_api_flavor",
        "IpAccess": 3,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "kubernetes",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "c2f8b64b-b3bf-46da-8649-18d14a0541cc",
        "Region": "EU",
        "ClusterName": "autoclusterandydnsapp",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "verificationCloudlet",
        "Flavor": "automation_api_flavor",
        "IpAccess": 3,
        "CloudletLocation": "-",
        "State": 4,
        "Progress": "",
        "Status": {
            "task_number": 1,
            "task_name": "Creating Heat Stack for verificationcloudlet-autoclusterandydnsapp-mobiledgex",
            "step_name": "Heat Stack Status: CREATE_FAILED"
        },
        "Reservable": "NO",
        "Deployment": "kubernetes",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "a0f144c0-4393-4f18-901e-347054a81dc7",
        "Region": "EU",
        "ClusterName": "andyded",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationDusseldorfCloudlet",
        "Flavor": "flavor1588097653-138105",
        "IpAccess": 1,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "docker",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "29f7a358-0f78-4e70-b150-fa1d6e1a590d",
        "Region": "EU",
        "ClusterName": "multiple",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationHamburgCloudlet",
        "Flavor": "automation_api_flavor",
        "IpAccess": 3,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "kubernetes",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "e7855cc3-f8a1-413d-aa15-5ba616087f10",
        "Region": "EU",
        "ClusterName": "cluster158871680299202dockerdedicatedgpu",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "verificationCloudlet",
        "Flavor": "flavor158871680299202gpu",
        "IpAccess": 1,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "docker",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "0c9b632e-5833-453c-8ff8-1786db5e6d9e",
        "Region": "EU",
        "ClusterName": "cluster1588797625-969057",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationDusseldorfCloudlet",
        "Flavor": "flavor1588797625-969057",
        "IpAccess": 1,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "kubernetes",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "bb5b46e0-6e76-47f8-a440-b26f6b551b71",
        "Region": "EU",
        "ClusterName": "autoclusterandydockercomposeinput",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationHamburgCloudlet",
        "Flavor": "flavor1588611008-764431",
        "IpAccess": 1,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "docker",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "ded0f473-6752-43ac-acdd-0024045225cc",
        "Region": "EU",
        "ClusterName": "autoclusterandydnsapp",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationDusseldorfCloudlet",
        "Flavor": "automation_api_flavor",
        "IpAccess": 3,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "kubernetes",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "7f765b7a-71d0-42c3-a32d-0794be7c7566",
        "Region": "EU",
        "ClusterName": "andyk8sded",
        "OrganizationName": "MobiledgeX",
        "Operator": "TDG",
        "Cloudlet": "automationDusseldorfCloudlet",
        "Flavor": "flavor1588633539-038995",
        "IpAccess": 1,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "kubernetes",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    },
    {
        "uuid": "b281cc44-743f-4079-a2c1-6078a0789662",
        "Region": "US",
        "ClusterName": "autoclusterautomation",
        "OrganizationName": "MobiledgeX",
        "Operator": "tmus",
        "Cloudlet": "tmocloud-1",
        "Flavor": "automation_api_flavor",
        "IpAccess": 3,
        "CloudletLocation": "-",
        "State": 5,
        "Progress": "",
        "Status": {},
        "Reservable": "NO",
        "Deployment": "kubernetes",
        "Edit": [
            "Region",
            "ClusterName",
            "OrganizationName",
            "Operator",
            "Cloudlet",
            "Flavor",
            "IpAccess",
            "Number_of_Master",
            "Number_of_Node",
            "CloudletLocation"
        ]
    }
]

const treeData = [
    {
        title: 'Node1',
        value: '0-0',
        children: [
            {
                title: 'Child Node1',
                value: '0-0-1',
            },
            {
                title: 'Child Node2',
                value: '0-0-2',
            },
        ],
    },
    {
        title: 'Node2',
        value: '0-1',
    },
];


let cloudletList = [
    "automationDusseldorfCloudlet",
    "automationHamburgCloudlet",
    "automationMunichCloudlet",
    "verificationCloudlet",
    "automationFrankfurtCloudlet",
    "automationBerlinCloudlet",
    "tmocloud-1"
]

let newCloudletList = []
newCloudletList.push({
    title: 'Reset Filter',
    value: '',
    selectable: true,
    children: []
});
cloudletList.map(cloudletOne => {

    let newCloudletOne = {
        title: cloudletOne,
        value: cloudletOne,
        selectable: false,
        children: []
    };

    clusterList.map(clusterOne => {
        if (clusterOne.Cloudlet === cloudletOne) {
            console.log(`sldkfldskflkdsf===>`, clusterOne);
            newCloudletOne.children.push({
                title: clusterOne.ClusterName,
                value: clusterOne.ClusterName + " | " + cloudletOne,
                isParent: false,
            })
        }
    })

    newCloudletList.push(newCloudletOne);
})


console.log(`sldkfldskflkdsf===>`, newCloudletList);
