// @flow
import {LineChart} from "reaviz";
import React, {useEffect, useState} from 'react';
import {AreaSeries, Borders, GradientDefs, HorizontalGridLines, VerticalGridLines, XYPlot, YAxis} from "react-vis";
import XAxis from "react-vis/es/plot/axis/x-axis";

const data = [
    {key: 'IDS', data: 14},
    {key: 'Malware', data: 5},
    {key: 'DLP', data: 18}
];

const data2 = [
    {
        "cluster": "autoclustermobiledgexsdkdemo",
        "cloudletLocation": "-",
        "dev": "EU",
        "cloudlet": "RahDemo",
        "operator": "TDG",
        "sumUdpSent": 0,
        "sumUdpRecv": 0,
        "sumUdpRecvErr": 0,
        "sumTcpConns": 0,
        "sumTcpRetrans": 0,
        "sumSendBytes": 0,
        "sumRecvBytes": 0,
        "sumMemUsage": 0,
        "sumDiskUsage": 0,
        "sumCpuUsage": 0,
        "columns": 0,
        "udpSeriesList": [],
        "tcpSeriesList": [],
        "networkSeriesList": [],
        "memSeriesList": [],
        "diskSeriesList": [],
        "cpuSeriesList": []
    },
    {
        "cluster": "mexdemo-stage",
        "cloudletLocation": "-",
        "dev": "EU",
        "cloudlet": "mexplat-stage-berlin-cloudlet",
        "operator": "TDG",
        "sumUdpSent": 0,
        "sumUdpRecv": 0,
        "sumUdpRecvErr": 0,
        "sumTcpConns": 0,
        "sumTcpRetrans": 0,
        "sumSendBytes": 0,
        "sumRecvBytes": 0,
        "sumMemUsage": 0,
        "sumDiskUsage": 0,
        "sumCpuUsage": 0,
        "columns": 0,
        "udpSeriesList": [],
        "tcpSeriesList": [],
        "networkSeriesList": [],
        "memSeriesList": [],
        "diskSeriesList": [],
        "cpuSeriesList": []
    },
    {
        "cluster": "mexdemo-stage",
        "cloudletLocation": "-",
        "dev": "EU",
        "cloudlet": "mexplat-stage-frankfurt-cloudlet",
        "operator": "TDG",
        "sumUdpSent": 3344,
        "sumUdpRecv": 4022003,
        "sumUdpRecvErr": 0,
        "sumTcpConns": 9,
        "sumTcpRetrans": 5,
        "sumSendBytes": 634804.8,
        "sumRecvBytes": 357707.8,
        "sumMemUsage": 19.58573995384769,
        "sumDiskUsage": 7.055505077384209,
        "sumCpuUsage": 1.9486412843774032,
        "columns": [
            "time",
            "cluster",
            "clusterorg",
            "cloudlet",
            "cloudletorg",
            "cpu",
            "mem",
            "disk",
            "sendBytes",
            "recvBytes",
            "tcpConns",
            "tcpRetrans",
            "udpSent",
            "udpRecv",
            "udpRecvErr"
        ],
        "udpSeriesList": [
            [
                "2020-04-08T08:35:10.913000106Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                3344,
                4022413,
                0
            ],
            [
                "2020-04-08T08:34:35.104000091Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                3344,
                4022232,
                0
            ],
            [
                "2020-04-08T08:33:59.434999942Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                3344,
                4022049,
                0
            ],
            [
                "2020-04-08T08:33:24.069000005Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                3344,
                4021844,
                0
            ],
            [
                "2020-04-08T08:32:13.260999917Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                3344,
                4021477,
                0
            ]
        ],
        "tcpSeriesList": [
            [
                "2020-04-08T08:35:07.174999952Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                9,
                5,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:34:31.344000101Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                9,
                5,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:55.693000078Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                9,
                5,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:44.683000087Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                9,
                5,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:31:33.892999887Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                9,
                5,
                null,
                null,
                null
            ]
        ],
        "networkSeriesList": [
            [
                "2020-04-08T08:35:05.141999959Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                633623,
                341506,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:34:29.323999881Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                621362,
                355239,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:53.849999904Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                650933,
                367916,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:18.213999986Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                651269,
                371412,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:42.780999898Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                null,
                616837,
                352466,
                null,
                null,
                null,
                null,
                null
            ]
        ],
        "memSeriesList": [
            [
                "2020-04-08T08:34:59.54399991Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                19.58040640652004,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:34:23.421000003Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                19.581874355325816,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:48.105000019Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                19.579672432117153,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:12.516999959Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                19.575757901968423,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:37.056999921Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                19.610988673307013,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ]
        ],
        "diskSeriesList": [
            [
                "2020-04-08T08:35:01.426000118Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                7.058531142154599,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:34:25.444999933Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                7.057236437364274,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:49.964999914Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                7.055510984782493,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:14.51999998Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                7.053770763705004,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:39.059999942Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                null,
                null,
                7.052476058914681,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ]
        ],
        "cpuSeriesList": [
            [
                "2020-04-08T08:34:57.535000085Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                1.8909552301282662,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:34:21.414000034Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                1.9843752904595149,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:46.063999891Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                1.8826400524019995,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:35.184999942Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                1.9775463541304112,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:00.052999973Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-frankfurt-cloudlet",
                "TDG",
                2.007689494766825,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ]
        ]
    },
    {
        "cluster": "mexdemo-stage",
        "cloudletLocation": "-",
        "dev": "EU",
        "cloudlet": "mexplat-stage-hamburg-cloudlet",
        "operator": "TDG",
        "sumUdpSent": 3382,
        "sumUdpRecv": 3992834.6,
        "sumUdpRecvErr": 0,
        "sumTcpConns": 9,
        "sumTcpRetrans": 3,
        "sumSendBytes": 641376.8,
        "sumRecvBytes": 350057,
        "sumMemUsage": 20.281919568149032,
        "sumDiskUsage": 7.225102051536044,
        "sumCpuUsage": 2.215924843089064,
        "columns": [
            "time",
            "cluster",
            "clusterorg",
            "cloudlet",
            "cloudletorg",
            "cpu",
            "mem",
            "disk",
            "sendBytes",
            "recvBytes",
            "tcpConns",
            "tcpRetrans",
            "udpSent",
            "udpRecv",
            "udpRecvErr"
        ],
        "udpSeriesList": [
            [
                "2020-04-08T08:34:25.891000032Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                3383,
                3993862,
                0
            ],
            [
                "2020-04-08T08:33:14.585000038Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                3382,
                3993457,
                0
            ],
            [
                "2020-04-08T08:30:52.492000102Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                3382,
                3992680,
                0
            ],
            [
                "2020-04-08T08:29:40.85800004Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                3382,
                3992297,
                0
            ],
            [
                "2020-04-08T08:28:29.586999893Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                3381,
                3991877,
                0
            ]
        ],
        "tcpSeriesList": [
            [
                "2020-04-08T08:34:21.957999944Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                9,
                3,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:46.451999902Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                9,
                3,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:10.815999984Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                9,
                3,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:35.260999917Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                9,
                3,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:31:59.703000068Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                null,
                null,
                9,
                3,
                null,
                null,
                null
            ]
        ],
        "networkSeriesList": [
            [
                "2020-04-08T08:34:56.046999931Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                664569,
                351764,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:44.423000097Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                659667,
                346603,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:33.336999893Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                621902,
                345873,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:31:57.818000078Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                636749,
                355812,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:31:22.447000026Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                null,
                623997,
                350233,
                null,
                null,
                null,
                null,
                null
            ]
        ],
        "memSeriesList": [
            [
                "2020-04-08T08:34:50.266000032Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                20.298282304170737,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:34:14.392999887Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                20.27822033715848,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:38.779000043Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                20.275847153255814,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:03.144000053Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                20.284336790515876,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:27.658999919Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                20.272911255644264,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ]
        ],
        "diskSeriesList": [
            [
                "2020-04-08T08:34:52.130000114Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                7.229417405981664,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:40.676000118Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                7.226387402945754,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:05.025000095Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                7.224669334611826,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:29.559999942Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                7.223377091237452,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:31:54.042999982Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                null,
                null,
                7.221659022903524,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ]
        ],
        "cpuSeriesList": [
            [
                "2020-04-08T08:34:48.390000104Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                2.3549963184917715,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:33:36.880000114Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                2.199823681951927,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:32:25.765000104Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                2.122626734471703,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:31:50.138000011Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                2.148810521484262,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "2020-04-08T08:31:14.892999887Z",
                "mexdemo-stage",
                "MobiledgeX",
                "mexplat-stage-hamburg-cloudlet",
                "TDG",
                2.253366959045657,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ]
        ]
    }
]

export const electric = [
    {
        key: new Date("2019-01-01T06:00:00.000Z"),
        data: 49
    },
    {
        key: new Date("2019-02-01T06:00:00.000Z"),
        data: 93
    },
    {
        key: new Date("2019-03-01T06:00:00.000Z"),
        data: 44
    },
    {
        key: new Date("2019-04-01T06:00:00.000Z"),
        data: 28
    }
];

export const food = [
    {
        key: new Date("2019-01-01T06:00:00.000Z"),
        data: 169
    },
    {
        key: new Date("2019-02-01T06:00:00.000Z"),
        data: 84
    },
    {
        key: new Date("2019-03-01T06:00:00.000Z"),
        data: 86
    },
    {
        key: new Date("2019-04-01T06:00:00.000Z"),
        data: 206
    }
];

export const multi = [
    {
        key: "Electricity",
        data: electric
    },
    {
        key: "Food",
        data: food
    }
];

export const electric002 = [
    {
        key: new Date("2019-01-01T06:00:00.000Z"),
        data: 49
    },
    {
        key: new Date("2019-02-01T06:00:00.000Z"),
        data: 93
    },
    {
        key: new Date("2019-03-01T06:00:00.000Z"),
        data: 44
    },
    {
        key: new Date("2019-04-01T06:00:00.000Z"),
        data: 28
    }
];


export default function GradientExample(props) {
    return (
       <div st>
           <XYPlot xDomain={[1.2, 3]} yDomain={[11, 26]} width={800} height={500}>
               <GradientDefs>
                   <linearGradient id="CoolGradient" x1="0" x2="0" y1="0" y2="1">
                       <stop offset="0%" stopColor="red" stopOpacity={0.4}/>
                       <stop offset="100%" stopColor="blue" stopOpacity={0.3}/>
                   </linearGradient>
               </GradientDefs>
               <VerticalGridLines/>
               <HorizontalGridLines/>

               <AreaSeries
                   color={'url(#CoolGradient)'}
                   data={[
                       {x: 1, y: 10, y0: 10},
                       {x: 2, y: 25, y0: 5},
                       {x: 3, y: 15, y0: 3}
                   ]}
               />
               <Borders
                   style={{
                       bottom: {fill: '#fff'},
                       left: {fill: '#fff'},
                       right: {fill: '#fff'},
                       top: {fill: '#fff'}
                   }}
               />
               <XAxis/>
               <YAxis/>
               {/* <AreaSeries
                data={[
                    {x: 1, y: 5, y0: 6},
                    {x: 2, y: 20, y0: 11},
                    {x: 3, y: 10, y0: 9}
                ]}
            />*/}
           </XYPlot>
       </div>
    );
}
